"""Compatibility re-export. Prefer meal_planner_app.domain.* for new code."""

from meal_planner_app.domain._dao import get_dao, set_dao
from meal_planner_app.domain.ingredients import (
    DuplicateIngredientNameError,
    IngredientInUseError,
    create_master_ingredient,
    delete_master_ingredient,
    get_master_ingredient,
    get_master_ingredient_by_name,
    get_recipes_for_ingredient,
    list_ingredients_summary,
    list_unique_ingredient_names,
    list_unique_locations,
    list_unique_units,
    update_master_ingredient,
)
from meal_planner_app.domain.meal_plans import (
    add_recipe_to_meal_plan,
    create_meal_plan,
    delete_meal_plan,
    get_meal_plan,
    list_meal_plans,
    remove_recipe_from_meal_plan,
    reset_meal_plans_db,
    update_meal_plan,
)
from meal_planner_app.domain.recipes import (
    create_recipe,
    delete_recipe,
    get_recipe,
    list_recipes,
    reset_recipes_db,
    search_recipes,
    update_recipe,
)
from meal_planner_app.domain.shopping import (
    create_shopping_list,
    delete_shopping_list,
    generate_shopping_list,
    get_shopping_list,
    list_shopping_lists,
    reset_shopping_lists_db,
    shopping_list_to_pdf_data,
    update_shopping_list,
)

__all__ = [
    "set_dao",
    "get_dao",
    "create_recipe",
    "get_recipe",
    "update_recipe",
    "delete_recipe",
    "list_recipes",
    "search_recipes",
    "create_meal_plan",
    "get_meal_plan",
    "list_meal_plans",
    "update_meal_plan",
    "delete_meal_plan",
    "add_recipe_to_meal_plan",
    "remove_recipe_from_meal_plan",
    "generate_shopping_list",
    "shopping_list_to_pdf_data",
    "create_shopping_list",
    "get_shopping_list",
    "list_shopping_lists",
    "update_shopping_list",
    "delete_shopping_list",
    "list_unique_ingredient_names",
    "list_unique_locations",
    "list_unique_units",
    "list_ingredients_summary",
    "get_recipes_for_ingredient",
    "get_master_ingredient",
    "get_master_ingredient_by_name",
    "create_master_ingredient",
    "update_master_ingredient",
    "delete_master_ingredient",
    "DuplicateIngredientNameError",
    "IngredientInUseError",
    "reset_recipes_db",
    "reset_meal_plans_db",
    "reset_shopping_lists_db",
]
